### ISSUE TITLE
ZAP_2_9_0: Unable to install ZAP_2_9_0_windows.exe

### ISSUE THREAD

**Issue by zosrothko** [OWASP/www-project-zap#24]
Hello

I downloaded the latest ZAP version as ZAP_2_9_0_windows.exe for a 64 JVM and it does not install. See the log

[i4j_nlog_2.log](https://github.com/OWASP/www-project-zap/files/5511884/i4j_nlog_2.log)

Java 8 is fully operational
C:\Users\S853159>java -version
Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files (x86)\Micro Focus\Unified Functional Testing\bin\java_shared\classes\jasmine.jar"
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

C:\Users\S853159>where java
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe
C:\Program Files (x86)\Java\jre8\bin\java.exe

**Comment by psiinon** [comment]
Please raise this on the ZAP repo: https://github.com/zaproxy/zaproxy/issues
TBH I didnt realise issues were enabled on this one, I'll disable them now...
