### ISSUE TITLE
Issue with ZAP not loading JS

### ISSUE THREAD

**Issue by JsphByd** [OWASP/www-project-zap#38]
**Describe the bug**
A clear and concise description of what the owasp.org/www-project-zap content issue is.

I'm building a honeypot to track attacker behavior - it currently works by collecting the user behavior through a JS function inside of the fake website. However, we've noticed that when using OWASP ZAP that it doesn't trigger the JS function inside the fake website (we also tested the JS with burp, which triggered the function). Is this an intentional feature or if there's an option we need to change to load the JS?

**Comment by psiinon** [comment]
Please ask this on the ZAP User Group: https://groups.google.com/group/zaproxy-users
FYI ZAP is no longer an OWASP project...
